### PR TITLE
chmod +x the executable

### PR DESCRIPTION
**Pull request by ghost**
the prev PR didn't chmod a+x the executable. because i never used the github command line, so i just used "Add files via upload" lmao, after a ton of searching, i finally changed the mode to +x, just a simple `git update-index --chmod=+x snake.sh`, `git commit -m "chmod a+x the executable" ` and then finally `git push` although i had to create a token.

i also commented on the snake r/linux post, but looks like my new reddit account is too new, aw mann

### CODE REVIEW

**Comment by wick3dr0se** [comment]
That's odd. I didn't modify it myself but usually I just do a `chmod a+x <file>` and then `git add .`, `git commit -m '<msg>'` and `git push`. I just stick to the simple git stuff lol. Merging the PR

**Comment by ghost** [comment]
> That's odd. I didn't modify it myself but usually I just do a `chmod a+x <file>` and then `git add .`, `git commit -m '<msg>'` and `git push`. I just stick to the simple git stuff lol. Merging the PR

lmao, 4 commands instead of 3. also, snake was gonna be my first rust-written game, however i haven't fully learnt rust, just a bit (including enums, sturcts, strings, etc)

**Comment by wick3dr0se** [comment]
@o69mar True lol. Rust is where its at these days. Definitely a good project to start learning and ANSI escape sequences are good for any programming language but of course libraries exist

**Comment by ghost** [comment]
> @o69mar True lol. Rust is where its at these days. Definitely a good project to start learning and ANSI escape sequences are good for any programming language but of course libraries exist

@wick3dr0se yeah, once I fully learnt rust, I can finally make my first rust app.  also the repo is now 15 stars away from bypassing my repo in stars lmao.

i also have to install the colored crate using `cargo install` to print colors in rust. aw mann

**Comment by wick3dr0se** [comment]
I use projects like this to learn the languages. I spend a week or so learning the languages by reading and taking notes and then start writing the most junk program I can. That's what `sysfetch` was on first commit. All the haters and positive feedback alike, helped me learn a ton


Try raw ANSI escape sequences in Rust. Idk what you use to output text like echo/printf in BASH but you should be able to just `<printf> '\e[32m I am GREEN\e[m'`

**Comment by wick3dr0se** [comment]
@o69mar

**Comment by ghost** [comment]
same with ramfetch. i leanred much from the feedback. including using printf instead of echo.

well that didn't work

20230112_19h17m52s_grim

rust also uses println/print instead of printf, and i forgot the semicolon, dang it

**Comment by wick3dr0se** [comment]
@o69mar

Yea `echo` although more convienent sometimes, is always slower than `printf` in BASH. BASH has a lot of hidden features I'm always learning. Maybe the \033 unicode escape then, something like:

`println(r"\033[32m I am GREEN\033[m");`

**Comment by ghost** [comment]
> @o69mar
> 
> Yea `echo` although more convienent sometimes, is always slower than `printf` in BASH. BASH has a lot of hidden features I'm always learning. Maybe the \033 unicode escape then, something like:
> 
> `println(r"\033[32m I am GREEN\033[m");`

@wick3dr0se 

aw man, it doesn't work.

20230112_19h50m44s_grim

edit: i fixed it by using the colored crate, and i had to create a cargo project using `cargo new example` and then include colored in cargo.toml.

20230112_20h03m15s_grim

and it was very simple lmao
```rust
use colored::*;

fn main() {
     println!("{}", "I am GREEN".green());
}
```

**Pull request merged**
